### ISSUE TITLE
BUG: Chapter 7.4 not shown in static site

### ISSUE THREAD

**Issue by jarmokivekas** [hotosm/toolbox#7]
Whlie setting up for work on #6 , I noticed there is a markdown file for chapter 7.4 in the repo, but it does not appear on the static site when running `hugo serve` locally.

![image](https://user-images.githubusercontent.com/3074453/77555320-cc15a180-6ebf-11ea-9352-29a7eb15aaeb.png)

Not sure if this is actually a mistake or if it is intentionally not rendered somehow (there is not a lot of content on the page).

**Comment by jessbeutler** [comment]
Hey @jarmokivekas 

Thanks for flagging. 7.4 was pulled from the main production launch due to resource/time constraints. That's why it has a placeholder page but is not rendered. 

Feel free to re-order your "QGIS Workflows for Disaster Mapping" page as 7.4, and we'll make the other one 7.5 when it is completed eventually.

**Comment by jarmokivekas** [comment]
Ok, great.

Closing this as intentional, not a bug,
